---
title: "Rapport"
author: "Johan"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE}
library(pxweb)
pxweb_query_list <- 
  list("Region"=c("00"),
       "Alder"=c("tot"),
       "Kon"=c("1","2"),
       "ContentsCode"=c("BE0101A9"),
       "Tid"=c("2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023"))

# Download data 
px_data <- 
  pxweb_get(url = "https://api.scb.se/OV0104/v1/doris/sv/ssd/BE/BE0101/BE0101A/FolkmangdNov",
            query = pxweb_query_list)

# Convert to data.frame 
px_data_frame <- as.data.frame(px_data, column.name.type = "text", variable.value.type = "text")

# Get pxweb data comments 
px_data_comments <- pxweb_data_comments(px_data)
px_data_comments_df <- as.data.frame(px_data_comments)
```

## En tabell över data

```{r, echo=FALSE}
knitr::kable(head(px_data_frame))
```


## En plot över åren

```{r}
plot(x = px_data_frame$år, y = px_data_frame$`Folkmängden den 1 november`, type = "l")
```


